### PR TITLE
Adding the needed file to use Git LFS.

### PR DESCRIPTION
**Pull request by DiTo04**
A small PR to incorporate LFS in master to then be merged into #33. If LFS integration should just be done on #33 directly please reject me! :)

### CODE REVIEW

**Comment by DiTo04** [comment]
Should also mention that I added some ignores that is needed on my own system ^^

**Comment by Frost** [comment]
Do we even need Git LFS? Isn't that a bit overkill for a couple of font files?

**Comment by maxnordlund** [comment]
I'm think it's nice to have since we're probably gonna check in images, and over time new versions. Also PDF:s, mp3:s and even video. I rather have it in now then have to pull out git `git filter-branch`.

**Comment by DiTo04** [comment]
Cool! Did not know about the global gitignore...

**Comment by maxnordlund** [comment]
"The more you know"

**Comment by DiTo04** [comment]
On the note of the need for LFS: Are we really going to need to have pdfs and videos as part of the server code? Content for the website should be uploaded to the server database and be stored there.

**Comment by maxnordlund** [comment]
I'm not sure, but it can be done using it without killing the repo size. You should probably squash your commits, git rebase -i and follow the instructions to remove the two last ones.

**Comment by Frost** [comment]
I was under the impression that we should use the CMS to upload images, videos, PDF:s etc. The whole point of the CMS is to not need developers around to modify the web page.

**Comment by Frost** [comment]
Oh, and also, if we "need" to add LFS because of a couple of font files, then I believe those fonts are probably too big to be loaded for each request. So no, I don't think we should need LFS. On the other hand, I don't think we should have custom fonts either (for the logo, we could make a nice SVG instead), but I probably shouldn't bring up that discussion here.

**Comment by DiTo04** [comment]
@Frost I agree with you!

**Comment by maxnordlund** [comment]
Please delete the branch, always nice to keep our repo tidy (applies when merging as well).

**Pull request closed without merging**
