### PR TITLE
Add a .codeclimate.yml config file

### PR DESCRIPTION
**Pull request by Frost**
**Add a .codeclimate.yml config file**
Configure CodeClimate to not run a bunch of abundant checks.

Only analyze Python and JavaScript.

### CODE REVIEW

**Comment by maxnordlund** [comment]
Why not markdown and shellscript? I also think we shouldn't exclude the tests directory, but disable individual rules/engines when we see them as a problem, that way they stay formatted as pep8 for example.

**Comment by Frost** [comment]
Short version: because they weren't in the sample file I got from CodeClimate, and I forgot they have analyzers for those. 

What I mainly did was take the sample file and remove PHP, Perla, and Ruby from it. 

I can add those others again. Do we even have any shellscripts?

**Comment by maxnordlund** [comment]
😄  yeah I thought so. No we don't have any shellscript right now, but I really don't like having our CI setup live somewhere else so it _would_ be nice if we could move that stuff into the repo. I also would love a setup script(s), "Run setup.sh and it will do virtualenv, pip, docker-*, ...".

That, and if we add scripts, we'll get a pling if we made a boo boo.

**Comment by Frost** [comment]
@maxnordlund I added markdown and shellscript checking, and was rewarded with 3 markdown issues.

I think we should probably address those in other PRs though.

**Comment by maxnordlund** [comment]
Since we need the CI:s to be green I made a PR to fix the issues, this should be good after that.

**Comment by Frost** [comment]
@maxnordlund All checks pass.  Can I have a review now?

**Pull request merged**
