### PR TITLE
Flesh out model tests

### PR DESCRIPTION
**Pull request by Frost**
* Add conftest.py in `tickets/tests` with some fixtures
* Add validation test for `Ticket`
* Add very basic tests for `Show`

### CODE REVIEW

**Comment by maxnordlund** [comment]
Looks nice, maybe we can silence the dog. Seems a bit over zealous.

**Comment by Frost** [comment]
@maxnordlund I'm thinking if we either accidentally added hound twice and if I should look into that or just put it down... What do you think?

**Comment by maxnordlund** [comment]
Put it down for now, we need to think about how we want our style before we add it again, yes?

**Comment by maxnordlund** [comment]
I've merged this now, since we don't care about the dog.

**Pull request merged**
