### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by maxnordlund**
This fixes two security vulnerabilities in our dependencies. Unfortunately I wasn't able to install the python packages, and thus haven't tested this. @Frost could you take it for a spin, pretty please?

---

I just saw #88, let me adjust this PR. From +3,024 −1,029 to +1, -1 changes. Oh, the lock files.

### CODE REVIEW

**Comment by Frost** [comment]
I would _love_ for this to only be +1/-1.

Updating Django can unfortunately need some more fixing than just updating a version in a requirements file. Have you checked the official documentation on this and verified that we don't need to do anything else?

Here are a few useful links:

* [Upgrading Django to a newer version](https://django.readthedocs.io/en/1.11.x/howto/upgrade-version.html)
* [Release notes for Django 1.11](https://django.readthedocs.io/en/1.11.x/releases/1.11.html)
* [Deprecation timeline](https://django.readthedocs.io/en/1.11.x/internals/deprecation.html)
* [Django's release process](https://django.readthedocs.io/en/1.11.x/internals/release-process.html)

Regardless. I will take this for a spin and see if I can find out if and in that case why you are unable to install the packages.

**Comment by maxnordlund** [comment]
From what I remember when doing this the last time the changes were mechanical. As I said I can't seem to get pip to install, and also pyenv install 3.7.2 fails with a missing zlib (even though its there).

But yeah, this might need more work.

**Comment by maxnordlund** [comment]
https://django.readthedocs.io/en/1.11.x/releases/1.11.html#liveservertestcase-binds-to-port-zero <- but we don't use this yet, right?

https://django.readthedocs.io/en/1.11.x/releases/1.11.html#django-template-backends-django-template-render-prohibits-non-dict-context <- I think this is fine, but it's easy to fix if nothing else.

The tests (we don't have any but py.test runs) fails with

```
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/filer/models/__init__.py", line 3, in <module>
    from .clipboardmodels import *  # flake8: noqa
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/filer/models/clipboardmodels.py", line 9, in <module>
    from . import filemodels
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/filer/models/filemodels.py", line 18, in <module>
    from ..fields.multistorage_file import MultiStorageFileField
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/filer/fields/multistorage_file.py", line 12, in <module>
    from easy_thumbnails import fields as easy_thumbnails_fields
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/easy_thumbnails/fields.py", line 2, in <module>
    from easy_thumbnails import files
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/easy_thumbnails/files.py", line 14, in <module>
    from easy_thumbnails import engine, exceptions, models, utils, signals, storage
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/easy_thumbnails/engine.py", line 12, in <module>
    from easy_thumbnails import utils
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/easy_thumbnails/utils.py", line 15, in <module>
    from easy_thumbnails.conf import settings
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/easy_thumbnails/conf.py", line 334, in <module>
    settings = Settings()
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/easy_thumbnails/conf.py", line 21, in __init__
    super(AppSettings, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'settings_module'
```

Not sure about that, haven't used these packages myself.

**Comment by Frost** [comment]
The two things you linked to are probably entirely fine, yes. :)

**Comment by maxnordlund** [comment]
(Django 2.0 is much more [[fun]], every model and every migration needs to have  on_delete=CASCADE)

**Comment by Frost** [comment]
Yeah, I sort of dread that upgrade, but I really want to take care of that sometime "soon" as well. There are nice things in 2.x, and 1.11 won't be LTS forever...

**Comment by maxnordlund** [comment]
Yeah, but maybe let's at least upgrade to 1.11.

---

Then, if I remember correctly, you squash all migrations and add the now required on_delete option to all fields and the squashed migration. I think that's the big one. Maybe we need to upgrade some dependencies and some other mechanical changes but I think those are minor.

**Comment by Frost** [comment]
I do agree that when we get this branch to run and the server to work properly with these changes, I think we should definitely upgrade to 1.11.

**Comment by Frost** [comment]
I managed to get this running after upgrading `easy_thumbnails` as well. It is a transient dependency, required by `django_filer`, which in turn is required by `djangocms-picture`.

You could probably get the tests to run on CircleCI by bumping `v1` -> `v2` in [.circleci/config.yml](https://github.com/Karspexet/Karspexet/blob/master/.circleci/config.yml#L13). That will make CircleCI rebuild reinstall all the python packages.

When I run `PYTHONWARNINGS=always py.test`, I only seem to get warnings regarding stuff that is removed in 2.0, so I think this is fine.

Also, all tests do pass.

**Comment by Frost** [comment]
I just noticed that the newest version of django-cms (3.6.0, which is newer than the one I just upgraded this project to) will drop support for Django versions earlier than 1.11. On the other hand, it will introduce support for Django 2.0 and 2.1.

More info here: http://docs.django-cms.org/en/latest/upgrade/3.6.html

**Comment by maxnordlund** [comment]
That so good to hear ❤️

**Comment by Frost** [comment]
Et voilà! Green tests.

**Pull request merged**
