### PR TITLE
Update python requirements to latest versions

### PR DESCRIPTION
**Pull request by strokirk**
This PR depends on the directory change in https://github.com/Karspexet/Karspexet/pull/13 , but since they concern different topics I've split up the two.

### CODE REVIEW

**Comment by maxnordlund** [comment]
I forgot to mention the Makefile, as I said in #12 I don't think we should use make as our build system if we can avoid it. First, do we need a build system at all? Secondly, we should stick to python, so that new devs don't need to learn yet another arcane (but rock solid) tool from the 80's.

**Comment by strokirk** [comment]
Hm? But there isn't really a need for a description here? "Update python requirements to latest versions" is the full description of what the commit and PR does.

**Comment by maxnordlund** [comment]
That is that _what_ not the _why_. "I've updated the dependencies to the latest version, because ...". It also doesn't help that you have entangled the three PRs, so I don't really know what this does until they have been merge (in the correct order) _and_ this branch has been rebased.

So, please add a description of _why_ we need to apply this change.

**Comment by maxnordlund** [comment]
Oh, one thing could be, "I've updated foo from 2.x to 3.x", which helps to reduce noise when a bunch of other stuff also needed updating.

**Comment by strokirk** [comment]
Oops, the makefile commit should not be in this PR. I'll rebase and update once we've figured out how SemaphoreCI wants to be configured.

**Comment by strokirk** [comment]
> So, please add a description of why we need to apply this change.

I'm still not sure I follow, can you expand on this?

**Comment by maxnordlund** [comment]
When a new dev, or one of us far into the future, looks at any given PR, it should immediately be clear _why_ we introduced the changes in that PR. Of course you can argue that in _this_ case it's already obvious, but I do think we should't have any grey areas. So I would like to see some sort of description, even if it's just a simple "I've updated the dependencies, none were major version." or similar. The point is that, just like one should write clear commit messages (which you do), we should write clear PR messages, and not just chicken out with a oneliner.

**Comment by Frost** [comment]
"Update dependencies because there are newer versions available" seems like a fairly pointless description to me. When it comes to updating dependencies I think the _why_ is fairly obvious.

**Comment by strokirk** [comment]
> We should write clear PR messages, and not just chicken out with a oneliner.

Ah, sorry, I just felt that this early in the development cycle there was no need to keep old dependencies. Should have added that to the PR description. Please remind me in the future as well. But a little gentler, please. ;)

**Comment by maxnordlund** [comment]
Yeah, 😞 🐼

**Pull request merged**
